const MarkdownIt=require('markdown-it'),sanitize=require('sanitize-html'),hljs=require('highlight.js');
const fs=require('fs'),path=require('path'),crypto=require('crypto'),{execFile}=require('child_process');
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const md=new MarkdownIt({html:false,linkify:true,highlight:(source,lang)=>lang&&hljs.getLanguage(lang)?hljs.highlight(source,{language:lang}).value:''}).use(require('markdown-it-task-lists'),{enabled:false}).use(require('markdown-it-footnote'));
const fence=md.renderer.rules.fence;md.renderer.rules.fence=(tokens,i,options,env,self)=>{const t=tokens[i],lang=t.info.trim().toLowerCase();if(['plantuml','puml','mermaid'].includes(lang))return `<figure class="diagram-block" data-diagram="${lang==='puml'?'plantuml':lang}" data-source="${Buffer.from(t.content).toString('base64')}"><div class="diagram-output">图表加载中…</div><details><summary>图表源码</summary><pre><code>${escape(t.content)}</code></pre></details></figure>`;return fence(tokens,i,options,env,self);};
function render(source){return sanitize(md.render(String(source).slice(0,100000)),{allowedTags:[...sanitize.defaults.allowedTags,'img','input','figure','details','summary','del'],allowedAttributes:{...sanitize.defaults.allowedAttributes,'*':['class','id'],a:['href','title','target','rel'],img:['src','alt','title'],input:['type','checked','disabled'],figure:['class','data-diagram','data-source']},allowedSchemes:['http','https','mailto'],allowProtocolRelative:false,transformTags:{a:(_,attrs)=>({tagName:'a',attribs:{...attrs,...(attrs.href?.startsWith('#')?{}:{target:'_blank',rel:'noopener noreferrer'})}}),input:(_,attrs)=>({tagName:'input',attribs:{type:'checkbox',disabled:'',...(attrs.checked!=null?{checked:''}:{})}})}});}
function metrics(s,jobs){const used=jobs.filter(j=>!j.isBenchmark&&j.analysis?.skills.some(x=>x.id===s.id)),latest=new Map();for(const j of used.filter(j=>j.review?.rating))if(!latest.has(j.analysis.signature)||new Date(j.review.at)>new Date(latest.get(j.analysis.signature).review.at))latest.set(j.analysis.signature,j);const rated=[...latest.values()];return {used:used.length,confirmed:new Set(used.filter(j=>j.status==='resolved').map(j=>j.analysis.signature)).size,feedback:used.filter(j=>j.review?.accepted===false).length,ratingCount:rated.length,averageRating:rated.length?rated.reduce((a,j)=>a+j.review.rating,0)/rated.length:null,satisfaction:rated.length?100*rated.filter(j=>j.review.rating>=4).length/rated.length:null};}
function fallback(s){const manifest=JSON.parse(fs.readFileSync(path.resolve(__dirname,'../data/benchmark/manifest.json'),'utf8'));const cases=manifest.cases.filter(c=>c.category===s.category);return `## 分析建议\n\n${s.guidance}\n\n## 识别条件\n\n${s.patterns.map(p=>'\n- `'+p+'`').join('')}\n\n## 定位流程\n\n1. 保留完整日志、内核版本、配置与复现条件。\n2. 根据异常类型和调用栈筛选证据，核对对应版本源码。\n3. 对照社区案例，验证触发路径与修复是否适用。\n4. 复现与验证修复，记录结论；无法验证时交由专家复核。\n\n\`\`\`plantuml\n@startuml\nactor 测试人员\nparticipant 分析工作台\nparticipant 专家\n测试人员 -> 分析工作台 : 日志与复现条件\n分析工作台 -> 专家 : 证据、源码与候选根因\n专家 --> 测试人员 : 修复与验证建议\n@enduml\n\`\`\`\n\n## 社区案例\n\n${cases.length?cases.map(c=>`### ${c.symbol}\n\n${c.rootCause}\n\n| 项目 | 内容 |\n| --- | --- |\n| 内核 | ${c.kernelVersion} |\n| 修复 | ${c.fixTitle} |\n\n[原始日志](${c.reportUrl}) · [修复依据](${c.fixUrl})\n\n> ${c.rootCauseBasis}`).join('\n\n'):'暂无对应的社区案例。'}\n\n## 验证记录\n\n- [ ] 在匹配版本与配置下复现\n- [ ] 核对补丁与实际触发路径\n- [ ] 验证修复并提交任务评价`;}
module.exports={render,metrics,fallback,install(app,{state,data}){
 const dir=path.join(data,'diagram-cache');fs.mkdirSync(dir,{recursive:true});const runtime=path.resolve(__dirname,'../data/diagram-runtime');let running=0;const pending=new Map();
 const findJava=()=>{if(process.env.PLANTUML_JAVA)return process.env.PLANTUML_JAVA;const found=fs.existsSync(runtime)?fs.readdirSync(runtime).find(n=>(n.startsWith('jdk-')||n.startsWith('zulu'))):null;return found?path.join(runtime,found,'bin/java.exe'):'java';};
 app.get('/api/experiences/:id',(req,res)=>{const s=state.skills.find(s=>s.id===req.params.id);if(!s)return res.status(404).json({error:'经验不存在'});const content=s.content||fallback(s);res.json({id:s.id,name:s.name,version:s.version,contributor:s.contributor,team:s.team,category:s.category,status:s.status,content,html:render(content),...metrics(s,state.jobs)});});
 app.post('/api/markdown/preview',(req,res)=>{if(typeof req.body.content!=='string'||req.body.content.length>100000)return res.status(400).json({error:'内容最多 100000 字符'});res.json({html:render(req.body.content)});});
 app.get('/api/diagrams/:key.png',(req,res)=>{if(!/^[a-f0-9]{64}$/.test(req.params.key))return res.status(400).end();const file=path.join(dir,req.params.key+'.png');if(!fs.existsSync(file))return res.status(404).end();res.setHeader('Cache-Control','private, max-age=86400');res.type('png').sendFile(file);});
 app.post('/api/diagrams/plantuml',async(req,res)=>{const source=String(req.body.source||'');if(!source.trim()||source.length>20000)return res.status(400).json({error:'PlantUML 源码需为 1–20000 字符'});if(/!\s*(include|import)|%\s*(getenv|load|file|dirpath)|<img:|https?:\/\//i.test(source))return res.status(400).json({error:'图表不支持外部资源或文件引用'});const jar=process.env.PLANTUML_JAR||path.join(runtime,'plantuml.jar');if(!fs.existsSync(jar))return res.status(503).json({error:'本地 PlantUML 运行环境未准备好'});const text=/@start/.test(source)?source:'@startuml\n'+source+'\n@enduml';const key=crypto.createHash('sha256').update('plantuml-local-v1:'+text).digest('hex'),file=path.join(dir,key+'.png');if(fs.existsSync(file))return res.json({url:'/api/diagrams/'+key+'.png'});if(pending.has(key)){try{await pending.get(key);return res.json({url:'/api/diagrams/'+key+'.png'});}catch(e){return res.status(400).json({error:e.message});}}if(running>=2)return res.status(429).json({error:'图表渲染繁忙，请稍后重试'});running++;const job=new Promise((resolve,reject)=>{const child=execFile(findJava(),['-Xmx256m','-Djava.awt.headless=true','-DPLANTUML_SECURITY_PROFILE=SANDBOX','-DPLANTUML_LIMIT_SIZE=4096','-jar',jar,'-charset','UTF-8','-tpng','-pipe'],{encoding:'buffer',timeout:30000,maxBuffer:8*1024*1024,windowsHide:true},(error,out)=>{if(error)return reject(Error('PlantUML 渲染失败，请检查图表语法'));if(!out.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))return reject(Error('未生成有效图表'));fs.writeFileSync(file,out);resolve();});child.stdin.on('error',()=>{});child.stdin.end(text);});pending.set(key,job);try{await job;res.json({url:'/api/diagrams/'+key+'.png'});}catch(e){res.status(400).json({error:e.message});}finally{running--;pending.delete(key);}});
}};
